### ISSUE TITLE
Return the layer id in draw plugin

### ISSUE THREAD

**Issue by byzheng** [bhaskarvk/leaflet.extras#13]
Thanks for implementing draw plugin in leaflet.extras. Do you consider to implement to return layer id in all events? Like I have implemented here: https://github.com/byzheng/leaflet/blob/bc64ac8de5d009d083669b2562580fb55f46303d/inst/htmlwidgets/plugins/leaflet-draw-plugin/leaflet-draw-plugin.js

In my case, I need to link the layer id with other attributes after drawing a feature. This layer id can be used to retrieve attributes when a feature is edited and deleted, then execute extra steps, e.g. update or remove records from database.

**Comment by bhaskarvk** [comment]
Hi Bangyou,
Firstly thanks for the PRs, I was hoping someone would start contributing :). 

I do emit Shiny onInputChange event in case when a feature is created/edited/deleted. For those cases I add the ID of the layer (and radius in case of a circle) to the layer's properties.

https://github.com/bhaskarvk/leaflet.extras/blob/master/inst/htmlwidgets/lib/draw/draw-bindings.js#L60

I checked your code and I am doing more or less the same thing, except I'm encoding the ID in the properties of the GeoJSON features, rather than passing the ID array and the GeoJSON separately. 

I haven't added Shiny events for shape drag/resize-start/stop as they are intermediate events and I don't think anyone is necessarily interested in those intermediate states on the R side. But I would be more than happy to add them if someone has a use case for it.
